### ISSUE TITLE
New FV Map is Messed Up

### ISSUE THREAD

**Issue by Sooleawa2** [zajako/LineageHD#278] opened 2019-09-20 02:27 UTC
No mobs
Can't walk up from beach, all walls, no way to go up into FV
R-tele in to lower lava fields and couldn't move, no mobs also

**Comment by zajako** [comment] 2019-09-20 04:44
Valakas' Wrath Destroyed the mountain, not a bug, but I do need to move some of the important stuff from there, like a way to talk to the npc and the entrance to valakas' lair.

**Comment by zajako** [comment] 2019-09-20 08:25
I've moved the npcs and added a teleport option to their dragons.  Still need to code the links so teleport actually works.

**Comment by zajako** [comment] 2019-09-21 00:13
The Valakas and Antharas npcs are now near each other at the northern most point of FV. They will also now offer teleporting to Vala's Lair and Dragon Valley Caves 1st floor (so you can get to Antharas).

I'm closing this ticket now.

**Closed as completed by zajako** 2019-09-21 00:13 UTC
Labels: 6 - Done, Bug
