### ISSUE TITLE
Settings for shortcuts do not save.

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#151] opened 2019-06-19 18:24 UTC
Cannot save settings for shortcuts (potions, spells, etc). Exiting game does not save them and changing character crashes client so changing character also does not save them at this time.

**Comment by zajako** [comment] 2019-07-19 21:59
This issue is a duplicate of https://github.com/zajako/LineageHD/issues/60, closing for that reason.

**Closed by zajako** 2019-07-19 21:59 UTC
Labels: duplicate
