### ISSUE TITLE
Account not getting free rolls. 

### ISSUE THREAD

**Issue by RaginnFlame** [zajako/LineageHD#466] opened 2023-10-11 16:56 UTC
Zaj, Ive been having problem on not recieving any free rolls in mini game. Can you please fix it. 

I did check place items on the character and it shows it was logged in.

**Comment by zajako** [comment] 2023-10-11 19:46
Its not a bug, the event is over. The mini games will be closing soon as well.

**Closed as completed by zajako** 2023-10-11 19:46 UTC
