### ISSUE TITLE
Weapon AOE

### ISSUE THREAD

**Issue by Emberglin** [zajako/LineageHD#368] opened 2019-10-17 20:15 UTC
The AOE effect for some weapons (scatterblaster among a few others) needs to be changed to work like Vala sword or the Anth pole arm or the Zaj Blade of Truth. Meaning that the AOE needs to happen all at once and not separate individual hits with animation. This causes insta death by stun lock in any hunting ground that is not easy. This change is needed, I believe because this client is alot slower than the other, making all of these AOE animations last 3 or 4 times longer than with the old client. Your character cant move, walk or attack while cycling through these animations.

**Comment by zajako** [comment] 2019-10-17 21:43
I"m not lagging with scatterblaster aoe, I changed the way it worked since v4 which greatly improved it from the entrapment lag that you're referring to.

Large qty of mobs:
https://share.getcloudapp.com/E0uPrd0B 

High Hp Mobs:
https://share.getcloudapp.com/WnuArKe8


In the 2nd one I demonstrate stopping firing and trying to walk and it only has like a half second delay at most. This is also with cdk and full gm buffs.

What kind of video card do you have in your computer?

**Comment by Emberglin** [comment] 2019-10-17 21:50
I use bow morphs with bows, so try it unpolyed or in a bow morph. Cdk greatly speeds up the animations. I dont think it's a video card problem, I'm not having problems with anything else.

**Comment by zajako** [comment] 2019-10-17 21:52
I tested with the top bow morph, and didn't have the issue.

Then I used triple arrow. Triple arrow makes it much more noticeable of an issue. Can you try without triple arrow and see if it is a problem?

If the problem is Triple Arrow, maybe the solution will be to take away aoe from triple shots, which probably is something that should be done for balancing purposes anyways.

**Comment by Emberglin** [comment] 2019-10-17 21:52
Am I seeing you fire arrows long range with the cdk poly? We couldn't do that in version 4. If so, that might be a game changer.

**Comment by zajako** [comment] 2019-10-17 21:53
correct, you can do that, but no triple arrow in cdk poly still.

**Comment by Emberglin** [comment] 2019-10-17 21:54
That might be it, the tripple arrow.

**Comment by Emberglin** [comment] 2019-10-17 21:55
I was playing unpolyed because that was the only way tripple arrow worked. The aoe animations were ferocious!

**Comment by zajako** [comment] 2019-10-17 21:55
Triple arrow now works with all bow polys, that fix was put in this morning

**Comment by zajako** [comment] 2019-10-18 05:10
Test it now and let me know how triple arrow is with the animation lag

**Comment by zajako** [comment] 2019-10-22 03:28
I"m gonna assume this is now fixed and close it since it has been 4 days and I've seen no complaints on it. I personally tested and it seemed to be fine on my end as well.

**Comment by Emberglin** [comment] 2019-10-22 04:18
I'm sorry Zaj, I wanted to give you some time because you were on a roll with other fixes, but no, it's still maddening. The animations need to be eliminated and it should be like the melee ape weapons. Its especially bad on mops with alot of hit points, like bosses. I'm there for 20, 30 seconds after, still shooting at nothing. In fact, after ending the daily boss in the underground (I forget his name) I get timed out and teleported out before I can open one of the chests. It even does it in non aoe areas or when your behind an object and cant hit your target but still firing arrows. Please, it needs to be fixed.

**Comment by zoekobii** [comment] 2019-10-22 04:22
hmm, if it were an issue with the animations in general, then it would happen to me and everyone else.   The other people that use the scatterblastered that have tested have said at most they are stuck there for a half second, if they had been shooting for a while.

I don't want to simply switch the aoe to match the others, as otherwise I'd have to nerf the damage like the other aoes have. The multi shot feature itself slows down the attacks slightly enough to make it more balanced and fair. 

So I don't wanna just remove the animations, as I'd rather fix the cause of the issues.  Can you try typing -netdelay 5 and killing the underworld daily boss and seeing if it still does it?

**Comment by Emberglin** [comment] 2019-10-22 04:24
Np, I'll try.

**Comment by zoekobii** [comment] 2019-10-22 04:32
Also try with/without soulshots because apparently that matters (it really shouldn't)

**Comment by Emberglin** [comment] 2019-10-23 22:56
Ok, I did some testing. Zaj, I did what you told me concerning not using soul shots and typing -netdelay 5. Doing either of those things didnt affect a thing. The continual aoe animation lock was still fucking me. So then I tried all of the polys to see if there was any difference, there was with some. Here are my findings....the lvl 84 and the lvl 82 bow polys do not jive with the scatterblaster, same with being unpolyed. These 3 situations are unplayable using the scatterblaster and tripple arrow. I then tested with the lvl 80 poly, it worked noticeably better, not like before mind you but percievably better. The best by far was when I tested the dragon bow morph with it.  Although still not like before, it is playable. Would you consider adding that poly to Scatterblaster? Would solve a big problem without you having to change or tinker with much.

**Comment by Stardeepp** [comment] 2019-10-24 02:38
I just noticed something about attack animations. The effect is greater with crit hits and with triple arrow. Everything on the screen including my toon freezes for a split second with every attack sequence. Its like a total game freeze for a split second with every attack.

**Comment by zajako** [comment] 2019-10-24 06:26
I believe I've found the problem causing this issue and all freezes. I should have it fixed with the next restart. (hopefully tomorrow)

**Closed as completed** 2019-11-14 04:49 UTC
